# Generated by Django 5.0.2 on 2024-02-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.AddField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.cv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='core.personalinfo'),
        ),
    ]
